Paginate = 5
PreTitle = "NTT DATA"
Copyright = "Copyright 2021 NTT DATA Deutschland GmbH - This site does not use any cookies"
baseURL = "https://nttdata-dach.github.io/"
languageCode = "en-us"
publishDir = "publish/dev/"
theme = "ntt-data"
title = "Technology Blog"


[[params.navbar.nav]]
emphasized = true
name = "All Blogposts"
url = "/posts"
targetSelf = "true"

[[params.navbar.nav]]
name = "Contact"
url = "mailto:techblog@nttdata.com"

[[params.navbar.nav]]
name = "About Us"
url = "https://de.nttdata.com/"

[[params.footer.nav]]
name = "Imprint"
url = "/imprint"

[[params.footer.nav]]
name = "Privacy Notice"
url = "/privacy"

[[params.footer.nav]]
name = "Legal Notice"
url = "/legal"

[[params.footer.nav]]
name = "Contact"
url = "mailto:techblog@nttdata.com"

[taxonomies]
author = "authors"
tag = "tags"
