baseURL = "http://cps-tech-blog-draft.s3-website.eu-central-1.amazonaws.com/"
languageCode = "en-us"
title = "Technology Blog"
theme = "ntt-data"
Paginate = 5
PreTitle = "NTT DATA"
publishDir = "publish/dev/"

[[params.navbar.nav]]
  name = "All Blogposts"
  emphasized = true
  url = "/posts"

[[params.navbar.nav]]
  name = "Industrien"
  url = "/about"

[[params.navbar.nav]]
  name = "Services"
  url = "/about"

[[params.navbar.nav]]
  name = "About"
  url = "/about"

[taxonomies]
  tag = "tags"
