baseURL = "http://cps-tech-blog-draft.s3-website.eu-central-1.amazonaws.com/"
languageCode = "en-us"
title = "Technology Blog"
theme = "ntt-data"
Paginate = 5
PreTitle = "NTT DATA"
publishDir = "publish/dev/"

[taxonomies]
  tag = "tags"

[params]

    description = "Business Frontpage - A business home page starter template for Bootstrap 4 featuring marketing boxes and a full width image header"

    [params.navbar]
        name = "NTTData Technology Blog"
        url = "#"

        [[params.navbar.nav]]
        name = "All Blogposts"
        emphasized = true
        url = "/posts"

        [[params.navbar.nav]]
        name = "Industrien"
        url = "/about"

        [[params.navbar.nav]]
        name = "Services"
        url = "/about"
        
        [[params.navbar.nav]]
        name = "About"
        url = "/about"

    [params.header]
        name = "Trusted Global Innovator"
        tagline = "Putting Clients first"

    [params.summary]
        url = "#"
        [params.summary.description]

        [[params.summary.description.items]]
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. A deserunt neque tempore recusandae animi soluta quasi? Asperiores rem dolore eaque vel, porro, soluta unde debitis aliquam laboriosam. Repellat explicabo, maiores!"
        [[params.summary.description.items]]
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis optio neque consectetur consequatur magni in nisi, natus beatae quidem quam odit commodi ducimus totam eum, alias, adipisci nesciunt voluptate. Voluptatum."

        [params.summary.contact]
        name = "NTT DATA Deutschland GmbH"
        address1 = "Hans-Döllgast-Straße 26"
        address2 = "D-80807 München"
        phone = "+49 89 9936-0"
        email = "info_de@nttdata.com"



    [params.projects]

        [[params.projects.sections]]
        # title = "Section 1"

        [[params.projects.sections.rows]]
        # title = "Section 1, Row 1"

        [[params.projects.sections.rows.items]]
        title = "Example Project"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
        url = "projects/example"
        image = "covid.jpg"

        [[params.projects.sections.rows.items]]
        title = "Conneceted Car"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus totam ut praesentium aut."
        url = "projects/connected-car"
        image = "connected-car.jpg"

        [[params.projects.sections.rows.items]]
        title = "Card title 3"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque."
        url = "projects/hololens"
        image = "hololens.jpg"

        [[params.projects.sections.rows]]
        # title = "Section 1, Row 2"

        [[params.projects.sections.rows.items]]
        title = "NTT Security"
        description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente esse necessitatibus neque sequi doloribus."
        url = "#"
        image = "security.jpg"
