Paginate = 5
PreTitle = "NTT DATA"
Copyright = "Copyright 2021 NTT DATA EMEA - This site does not use any cookies"
baseURL = "http://cps-tech-blog-draft.s3-website.eu-central-1.amazonaws.com/"
languageCode = "en-us"
publishDir = "publish/dev/"
theme = "ntt-data"
title = "Technology Blog"


[[params.navbar.nav]]
emphasized = true
name = "All Blogposts"
url = "/posts"

[[params.navbar.nav]]
name = "Contact"
url = "mailto:github-emea@nttdata.com"

[[params.navbar.nav]]
name = "About Us"
url = "https://www.nttdata.com/global/en/"

[[params.footer.nav]]
name = "Privacy Policy"
url = "/privacy"

[[params.footer.nav]]
name = "Imprint"
url = "https://www.nttdata.com/global/en/term-of-use"

[[params.footer.nav]]
name = "Contact"
url = "mailto:github-emea@nttdata.com"

[taxonomies]
author = "authors"
tag = "tags"
